name: Deploy Nginx to Azure VM

on:
  push:
    branches:
      - main

jobs:
  install-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: install ssh client
      run: sudo apt-get install -y sshpass

    - name: Install Nginx on Azure VM
      run: |
        sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
        sudo apt update && sudo apt install -y nginx
        sudo systemctl enable nginx
        sudo systemctl start nginx
        sudo systemctl enable nginx
        EOF

    
